name: "Create Conan Package"
on: push

jobs:
  build_linux:
    name: "Linux"
    uses: Privatehive/conan-workflows/.github/workflows/createPackage.yml@master
    with:
      image: "ghcr.io/privatehive/conan-ubuntu:latest"
      machine_type: c2d-standard-8
      conan_remotes: https://conan.privatehive.de/artifactory/api/conan/public-conan
      conan_options: "plabels/*:shared=True"
      conan_deploy_artifacts: true

  upload_recipe:
    name: "Finalize"
    uses: Privatehive/conan-workflows/.github/workflows/uploadRecipe.yml@master
    needs: [ build_linux ]
    if: ${{ success() }}
    secrets: inherit
    with:
      publish_property: ${{ github.ref == 'refs/heads/master' }}
      conan_upload_remote: https://conan.privatehive.de/artifactory/api/conan/public-conan
